---
- name: Slurm conf demo
  hosts: localhost
  connection: local
  tasks:
    - name: Slurm conf demo
      slurm_conf:
        path: /root/ansible_collections/dell/omnia/slurm_sample_confs/slurm1.conf
        op: merge
        conf_sources:
          - /root/ansible_collections/dell/omnia/slurm_sample_confs/slurm1.conf
          - /root/ansible_collections/dell/omnia/slurm_sample_confs/slurm2.conf
      register: conf_out

    - name: Print the first elemnt of slurm_dict
      debug:
        var: conf_out.slurm_dict.keys()