# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
openchami_work_dir: "{{ hostvars['localhost']['oim_shared_path'] }}/omnia/openchami/workdir"
cluster_post:
  slurm_control_node_x86_64:
    runcmd:
      - systemctl restart slurmdbd
      - systemctl restart slurmctld
      - echo "SLURM_CONTROL_NODE_X86_64_Cloud-Init has completed successfully."
  slurm_node_x86_64:
    write_files:
      - path: /usr/local/bin/setup_nvhpc_sdk.sh
        owner: root:root
        permissions: '0755'
        content: |
          {{ lookup('template', 'setup_nvhpc_sdk.sh.j2') }}
      - path: /usr/local/bin/export_nvhpc_env.sh
        owner: root:root
        permissions: '0755'
        content: |
          {{ lookup('template', 'export_nvhpc_env.sh.j2') }}
    runcmd:
      - /usr/local/bin/setup_nvhpc_sdk.sh
      - /usr/local/bin/export_nvhpc_env.sh
      - systemctl restart slurmd
      - echo "SLURM_NODE_X86_64_Cloud-Init has completed successfully."
  login_node_x86_64:
    runcmd:
      - systemctl restart slurmd
      - echo "LOGIN_NODE_X86_64_Cloud-Init has completed successfully."
  login_node_aarch64:
    runcmd:
      - systemctl restart slurmd
      - echo "LOGIN_NODE_AARCH64_Cloud-Init has completed successfully."
  login_compiler_node_x86_64:
    write_files:
      - path: /usr/local/bin/install_nvhpc_sdk.sh
        owner: root:root
        permissions: '0755'
        content: |
          {{ lookup('template', 'install_nvhpc_sdk.sh.j2') }}
      - path: /usr/local/bin/configure_nvhpc_env.sh
        owner: root:root
        permissions: '0755'
        content: |
          {{ lookup('template', 'configure_nvhpc_env.sh.j2') }}
    runcmd:
      - /usr/local/bin/install_nvhpc_sdk.sh
      - /usr/local/bin/configure_nvhpc_env.sh
      - systemctl restart slurmd
      - echo "LOGIN_COMPILER_NODE_X86_64_Cloud-Init has completed successfully."
  login_compiler_node_aarch64:
    write_files:
      - path: /usr/local/bin/install_nvhpc_sdk.sh
        owner: root:root
        permissions: '0755'
        content: |
          {{ lookup('template', 'install_nvhpc_sdk.sh.j2') }}
      - path: /usr/local/bin/configure_nvhpc_env.sh
        owner: root:root
        permissions: '0755'
        content: |
          {{ lookup('template', 'configure_nvhpc_env.sh.j2') }}
    runcmd:
      - /usr/local/bin/install_nvhpc_sdk.sh
      - /usr/local/bin/configure_nvhpc_env.sh
      - systemctl restart slurmd
      - echo "LOGIN_COMPILER_NODE_AARCH64_Cloud-Init has completed successfully."
