# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# - name: activate virtual env
#   ansible.builtin.pip:
#     name: virtualenv
#     virtualenv: /home/jag/omnia/venvy/my_py_venv_311

# - name: shell activate
#   ansible.builtin.shell:
#     cmd: "source /home/jag/omnia/venvy/my_py_venv_311/bin/activate"

# - name: command activate
#   ansible.builtin.command: "source /home/jag/omnia/venvy/my_py_venv_311/bin/activate"
#   ignore_errors: true

# - name: raw activate
#   ansible.builtin.raw: "source /home/jag/omnia/venvy/my_py_venv_311/bin/activate"
#   ignore_errors: true

# - name: Set environment variable
#   environment:
#     VARIABLE_NAME: variable_value

# - name: Use the environment variable
#   shell: "echo The value of VARIABLE_NAME is: $VARIABLE_NAME"

# - name: shell env
#   ansible.builtin.shell: "export ANSIBLE_COLLECTIONS_PATH=/home/jag/omnia/venvy/my_py_venv_311/within_shell:/home/jag/.ansible/collections:/usr/share/ansible/collections"

# - ansible.builtin.debug:
    # msg: "Am looking for {{ lookup('ansible.builtin.ini', 'collections_path', section='defaults', file='ansible.cfg') }}"

#1 edit
#2 use



- name: Install dellemc.openmanage with environment
  ansible.builtin.command: ansible-galaxy collection install dellemc.openmanage --force -v
  # environment:
  #   ANSIBLE_COLLECTIONS_PATH: "/home/jag/omnia/venvy/my_py_venv_311/install_env:/home/jag/.ansible/collections:/usr/share/ansible/collections"

- name: Install my omniadummy collection
  ansible.builtin.command: ansible-galaxy collection install /home/jag/omnia/forked_omnia/local_repo/omnia/omnia-dummy-1.0.0.tar.gz --force -v

- name: Common prereqs
  ansible.builtin.import_tasks: add_pbook.yml

# - name: Run the dummy module
#   omnia.dummy.mymodule:
#     param1: "Will see this from roles/validation/tasks/main.yml"

# - name: Retrieve basic details of all user accounts.
#   dellemc.openmanage.idrac_user_info:
#     idrac_ip: "100.96.24.131"
#     idrac_user: "root"
#     idrac_password: "Dell_123$"
#     validate_certs: false

- name: Collect path
  ansible.builtin.debug:
    msg: "SECOND {{ lookup('ansible.builtin.env', 'ANSIBLE_COLLECTIONS_PATH') }}"

- name: Test virtualenv
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }} is the VENV"  

# - name: Test which virtualenv
#   ansible.builtin.command: which python3

# - name: Warning - Omnia will remove any package/software conflicting with the requirements
#   ansible.builtin.pause:
#     seconds: "{{ warning_wait_time_warning }}"
#     prompt: "{{ warning_msg_local_repo }}"

# - name: Validate control plane OS jag
#   ansible.builtin.include_tasks: validate_cp_os.yml

- name: Common prereqs
  ansible.builtin.include_tasks: common_requirements.yml

- name: Install prerequisites
  ansible.builtin.include_tasks: prerequisites_{{ ansible_distribution | lower }}.yml

- name: Validate software_config.json
  ansible.builtin.include_tasks: validate_software_config_json.yml

- name: Validate local_repo_config.yml
  ansible.builtin.include_tasks: validate_local_repo_config.yml

- name: Validate ubuntu_os_url
  ansible.builtin.include_tasks: validate_ubuntu_os_url.yml
  when: cluster_os_type == 'ubuntu'

- name: Validate software json files present in config directory
  ansible.builtin.include_tasks: validate_json_path.yml

- name: Validate metadata
  ansible.builtin.include_tasks: validate_metadata.yml

- name: Validate provision_config_credentials.yml
  ansible.builtin.include_tasks: validate_provision_config_credentials.yml

- name: Validate bcm_roce.json
  ansible.builtin.include_tasks: validate_bcm_roce_json.yml
