# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
tls_cert_path: "/etc/openldap/certs/ldapserver.crt"
ldap_conf_dest: "/etc/openldap/ldap.conf"
sasl_nocanon_regxp: "SASL_NOCANON\ton"
sasl_nacanon_replace1: "SASL_NOCANON\ton\nBASE\t{{ hostvars['localhost']['ldap_search_base'] }}"
sasl_nacanon_replace2: "SASL_NOCANON\ton\nURI\tldap://{{ hostvars['localhost']['ldap_server_ip'] }}"
sasl_nacanon_replace3: "SASL_NOCANON\ton\nTLS_CACERT\t{{ tls_cert_path }}"
sasl_nacanon_replace4: "SASL_NOCANON\ton\nURI\tldap://{{ hostvars['localhost']['ldap_server_ip'] }}:636"
file_mode: "0644"
ldap_starttls_port: 389
ldap_ssl_port: 636

openldap_fail_msg: "Failed to set the openldap params."
cloud_init_openldap:
  write_files:
    - path: /etc/sssd/sssd.conf
      owner: root:root
      permissions: '0600'
      content: |
        {{ lookup('template', 'sssd.conf.j2') }}

    - path: /usr/local/bin/update_ldap_conf.sh
      owner: root:root
      permissions: '0755'
      content: |
        {{ lookup('template', 'update_ldap_conf.sh.j2') }}

  runcmd:
    - /usr/local/bin/update_ldap_conf.sh
    - mkdir /ldapcerts
    - echo "{{ cloud_init_nfs_path_openldap }}/certs /ldapcerts nfs defaults,_netdev 0 0" >> /etc/fstab
    - echo "{{ cloud_init_nfs_path_openldap }}/ldapuser /home nfs defaults,_netdev 0 0" >> /etc/fstab
    - chmod 0644 /etc/fstab
    - mount -a
    - yes | cp /ldapcerts/* /etc/openldap/certs
    - umount /ldapcerts

    - firewall-cmd --permanent --add-port={{ ldap_starttls_port }}/tcp
    - firewall-cmd --permanent --add-port={{ ldap_ssl_port }}/tcp
    - firewall-cmd --reload

    - setenforce 0
    - authselect select sssd with-mkhomedir --force
    - sudo systemctl enable --now oddjobd.service
    - sudo systemctl enable --now sssd
    - setsebool -P authlogin_nsswitch_use_ldap on
    - setsebool -P authlogin_yubikey on
    - sudo systemctl restart sssd
    - systemctl restart sshd
