# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Merge slurm_config into slurm and login cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ item: (cloud_init_groups_dict[item] | combine(slurm_config, recursive=True, list_merge='append')) }) }}"
  loop: "{{ cloud_init_groups_dict.keys() | select('match', '^slurm') | list + cloud_init_groups_dict.keys() | select('match', '^login') | list }}"

- name: Create separate powervault group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'powervault': cloud_init_powervault }, recursive=True, list_merge='append') }}"
  when: powervault_config is defined

- name: Create separate nvidia_driver group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'nvidia_driver': cloud_init_nvidia_driver }, recursive=True, list_merge='append') }}"
  when: cloud_init_nvidia_driver is defined

- name: Merge the remaining parts if defined
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ item: (cloud_init_groups_dict[item] | combine(_slurm_config.get(item, {}), recursive=True, list_merge='append')) }) }}"
  loop: "{{ cloud_init_groups_dict.keys() | list }}"
  when: _slurm_config is defined

- name: Create separate apptainer group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'apptainer': cloud_init_apptainer }, recursive=True, list_merge='append') }}"
  when: cloud_init_apptainer is defined

- name: Create separate ucx_openmpi group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'ucx_openmpi': cloud_init_ucx_openmpi }, recursive=True, list_merge='append') }}"
  when: cloud_init_ucx_openmpi is defined

- name: Create separate munge group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'munge': cloud_init_munge }) }}"
  when: cloud_init_munge is defined

- name: Create seperate mariadb group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'mariadb': cloud_init_mariadb }) }}"
  when: cloud_init_mariadb is defined

- name: Create seperate slurmdbd group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'slurmdbd': cloud_init_slurmdbd }) }}"
  when: cloud_init_slurmdbd is defined

- name: Create seperate slurmctld group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'slurmctld': cloud_init_slurmctld }) }}"
  when: cloud_init_slurmctld is defined

- name: Create seperate ctld_track group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'ctld_track': ctld_track}) }}"
  when: ctld_track is defined

- name: Create seperate slurm_config group in cloud_init_groups_dict
  ansible.builtin.set_fact:
    cloud_init_groups_dict: "{{ cloud_init_groups_dict | combine({ 'slurm_config': slurm_config }) }}"
  when: slurm_config is defined
  
# - name: Write cloud-init template files
#   ansible.builtin.template:
#     src: "group-template.yaml.j2"
#     dest: "{{ cloud_init_dir }}/{{ item }}.yaml"
#     mode: "0644"
#   vars:
#     group_name: "{{ item }}"
#   loop:
#     - munge
#     - mariadb
#     - slurmdbd
#   when: vars['cloud_init_' + item] is defined
